### ISSUE TITLE
devise_jwt_secret_key is blank

### ISSUE THREAD

**Issue by ammar299** [leminh0796/grape-devise-jwt-example#1]
rails aborted!
KeyError: :devise_jwt_secret_key is blank
I am facing this issue what I have need to do please let me know if you any idea.

**Comment by leminh0796** [comment]
Hi @ammar299, the key devise_jwt_secret_key is saved in credentials.
Here's documentation: [Custom credentials](https://edgeguides.rubyonrails.org/security.html#custom-credentials)

You can see in config/initializers/devise.rb we have sth like:
`config.jwt do |jwt|
    jwt.secret = Rails.application.credentials.devise_jwt_secret_key!
  end`

This row will raise an error when devise_jwt_secret_key not found. Please edit the devise_jwt_secret_key in credentials to any cypher text. Example a credential file:

`secret_key_base: 83c8bc89350e83d701d0cdcff29c29a28a3159f414d9fa2017b832ffed27f75ffcec227d0621b811001a$`
`devise_jwt_secret_key: d5d73e04ba24d20b7cf36877e4b4b3120c1a75c9b33014eab90f36fff547426e3defe04a2ebd49$`
`ASSET_HOST: "http://localhost:3000"`
